<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$(MSBuildThisFileDirectory)msbuild/repository.props" />
  <!-- Modified by Steven T. Cramer -->
  <!-- Set common properties regarding assembly information and nuget packages -->
  <PropertyGroup>
    <Authors>Steven T. Cramer</Authors>
    <Product>TimeWarp Mediator</Product>
    <Copyright>Copyright Jimmy Bogard (original MediatR); TimeWarp Engineering (Unlicense)</Copyright>
    <PackageProjectUrl>https://github.com/TimeWarpEngineering/timewarp-mediator</PackageProjectUrl>
    <PackageTags>mediator;request;response;queries;commands;notifications;opensource;free;unlicense</PackageTags>
    <RepositoryUrl>https://github.com/TimeWarpEngineering/timewarp-mediator.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>Logo.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>

    <!-- Unified versioning for all packages -->
    <Version>13.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <NoWarn>$(NoWarn);CS1701;CS1702;CS1591</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Source code specific settings for stricter compilation -->
    <Nullable>enable</Nullable>
    <Features>strict</Features>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)TimeWarp.Mediator.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers"
                      PrivateAssets="all"
                      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)BannedSymbols.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TimeWarp.Build.Tasks" PrivateAssets="all" />
  </ItemGroup>
</Project>
