<!-- Modified by Steven T. Cramer -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Simple, unambitious mediator implementation in .NET</Description>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <LangVersion>10.0</LangVersion>
    <RootNamespace>TimeWarp.Mediator</RootNamespace>
    <AssemblyName>TimeWarp.Mediator</AssemblyName>
    <PackageId>TimeWarp.Mediator</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IsExternalInit">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\timewarp-mediator-contracts\timewarp-mediator-contracts.csproj" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
