#region Purpose
// Emits mediator.manifest.json v1 as the MediatorManifest.Json const (source generators cannot write loose files).
#endregion

namespace TimeWarp.Mediator.Generators;

internal static class ManifestEmitter
{
    internal static void Emit(SourceProductionContext context, MessageGraph graph)
    {
        string json = BuildJson(graph);
        string ns = graph.Membership.GeneratedNamespace;
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("public static class MediatorManifest");
        builder.AppendLine("{");
        builder.AppendLine("    public const int Version = 1;");
        builder.AppendLine("    public const string Json =");
        builder.Append("        @\"").Append(json.Replace("\"", "\"\"")).AppendLine("\";");
        builder.AppendLine("}");

        context.AddSource("MediatorManifest.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string BuildJson(MessageGraph graph)
    {
        StringBuilder builder = new();
        builder.Append('{');
        builder.Append("\"version\":1,");
        builder.Append("\"profile\":\"").Append(Escape(graph.Membership.Profile)).Append("\",");
        builder.Append("\"namespace\":\"").Append(Escape(graph.Membership.GeneratedNamespace)).Append("\",");
        builder.Append("\"requests\":[");
        for (int i = 0; i < graph.Requests.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(',');
            }

            RequestBinding request = graph.Requests[i];
            builder.Append('{');
            builder.Append("\"request\":\"").Append(Escape(request.RequestType.ToDisplayString())).Append("\",");
            builder.Append("\"response\":\"").Append(Escape(request.ResponseType.ToDisplayString())).Append("\",");
            builder.Append("\"handler\":\"").Append(Escape(request.HandlerType.ToDisplayString())).Append("\",");
            if (request.ScopeType is not null)
            {
                builder.Append("\"scope\":\"").Append(Escape(request.ScopeType.ToDisplayString())).Append("\",");
            }
            builder.Append("\"behaviors\":[");
            for (int b = 0; b < request.ClosedBehaviors.Length; b++)
            {
                if (b > 0)
                {
                    builder.Append(',');
                }

                builder.Append('"').Append(Escape(request.ClosedBehaviors[b].ToDisplayString())).Append('"');
            }

            builder.Append("]}");
        }

        builder.Append("],\"notifications\":[");
        for (int i = 0; i < graph.Notifications.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(',');
            }

            NotificationBinding notification = graph.Notifications[i];
            builder.Append('{');
            builder.Append("\"notification\":\"").Append(Escape(notification.NotificationType.ToDisplayString())).Append("\",");
            if (notification.ScopeType is not null)
            {
                builder.Append("\"scope\":\"").Append(Escape(notification.ScopeType.ToDisplayString())).Append("\",");
            }
            builder.Append("\"handlers\":[");
            for (int h = 0; h < notification.HandlerTypes.Length; h++)
            {
                if (h > 0)
                {
                    builder.Append(',');
                }

                builder.Append('"').Append(Escape(notification.HandlerTypes[h].ToDisplayString())).Append('"');
            }

            builder.Append("]}");
        }

        builder.Append("],\"membership\":[");
        IAssemblySymbol[] assemblies = graph.Membership.MemberAssemblies.OrderBy(a => a.Name, StringComparer.Ordinal).ToArray();
        for (int i = 0; i < assemblies.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(',');
            }

            builder.Append('"').Append(Escape(assemblies[i].Name)).Append('"');
        }

        builder.Append("]}");
        return builder.ToString();
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
