#region Purpose
// Emits sealed Mediator (unscoped), per-TScope Sender/Publisher, and Host MS.DI registration.
#endregion

#region Design
// Host profile resolves handlers/behaviors from IServiceProvider in compile-time order.
// Aot profile uses ServiceGen static fields (parameterless handlers only) and does not weave
// [assembly: MediatorBehavior] into Dispatch_*. CallSiteInlining prototype is the public
// static Dispatch_* method the interceptors would target.
// Unscoped Mediator is the default pipeline (no [MediatorScope]). Each TScope gets its own
// Sender and Publisher with a disjoint type switch — no runtime "is this my message?" filter.
#endregion

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using TimeWarp.Mediator.Analyzers;

namespace TimeWarp.Mediator.Generators;

internal static class MediatorEmitter
{
    private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

    internal static void Emit(SourceProductionContext context, MessageGraph graph)
    {
        context.AddSource("Mediator.g.cs", SourceText.From(EmitMediator(graph), Encoding.UTF8));

        foreach (INamedTypeSymbol scope in DistinctScopes(graph))
        {
            string suffix = ScopeSuffix(scope, graph);
            context.AddSource(
                "Sender_" + suffix + ".g.cs",
                SourceText.From(EmitScopedSender(graph, scope, suffix), Encoding.UTF8));
            context.AddSource(
                "Publisher_" + suffix + ".g.cs",
                SourceText.From(EmitScopedPublisher(graph, scope, suffix), Encoding.UTF8));
        }

        if (!graph.IsAotProfile)
        {
            context.AddSource("MediatorServiceCollectionExtensions.g.cs", SourceText.From(EmitRegistration(graph), Encoding.UTF8));
        }
    }

    private static string EmitMediator(MessageGraph graph)
    {
        List<RequestBinding> requests = RequestsFor(graph, scope: null);
        List<NotificationBinding> notifications = NotificationsFor(graph, scope: null);
        return EmitDispatcher(
            graph,
            className: "Mediator",
            interfaceList: "global::TimeWarp.Mediator.IMediator",
            requests,
            notifications,
            includeSend: true,
            includePublish: true,
            includeServiceGen: graph.IsAotProfile);
    }

    private static string EmitScopedSender(MessageGraph graph, INamedTypeSymbol scope, string suffix)
    {
        List<RequestBinding> requests = RequestsFor(graph, scope);
        return EmitDispatcher(
            graph,
            className: "Sender_" + suffix,
            interfaceList: "global::TimeWarp.Mediator.ISender<" + Fq(scope) + ">",
            requests,
            notifications: new List<NotificationBinding>(),
            includeSend: true,
            includePublish: false,
            includeServiceGen: false);
    }

    private static string EmitScopedPublisher(MessageGraph graph, INamedTypeSymbol scope, string suffix)
    {
        List<NotificationBinding> notifications = NotificationsFor(graph, scope);
        return EmitDispatcher(
            graph,
            className: "Publisher_" + suffix,
            interfaceList: "global::TimeWarp.Mediator.IPublisher<" + Fq(scope) + ">",
            requests: new List<RequestBinding>(),
            notifications,
            includeSend: false,
            includePublish: true,
            includeServiceGen: false);
    }

    private static string EmitDispatcher(
        MessageGraph graph,
        string className,
        string interfaceList,
        List<RequestBinding> requests,
        List<NotificationBinding> notifications,
        bool includeSend,
        bool includePublish,
        bool includeServiceGen)
    {
        string ns = graph.Membership.GeneratedNamespace;
        bool aot = graph.IsAotProfile;
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(";");
        builder.AppendLine();

        if (includeServiceGen)
        {
            EmitServiceGen(builder, graph);
        }

        builder.Append("public sealed class ").Append(className).Append(" : ").AppendLine(interfaceList);
        builder.AppendLine("{");
        if (!aot)
        {
            builder.AppendLine("    private readonly global::System.IServiceProvider ServiceProvider;");
            builder.AppendLine();
            builder.Append("    public ").Append(className).AppendLine("(global::System.IServiceProvider serviceProvider)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (serviceProvider is null)");
            builder.AppendLine("        {");
            builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(serviceProvider));");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        ServiceProvider = serviceProvider;");
            builder.AppendLine("    }");
        }
        else
        {
            builder.Append("    public ").Append(className).AppendLine("()");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
        }

        builder.AppendLine();
        if (includeSend)
        {
            EmitInterfaceSend(builder);
            EmitMonomorphicSend(builder, requests, aot);
            EmitObjectSend(builder, requests, aot);
            EmitStreams(builder);
            EmitDispatchMethods(builder, requests, aot);
        }

        if (includePublish)
        {
            EmitPublish(builder, notifications, aot);
        }

        if (includeSend)
        {
            builder.AppendLine();
            builder.AppendLine("    private static async global::System.Threading.Tasks.Task<object?> Box<T>(global::System.Threading.Tasks.ValueTask<T> valueTask)");
            builder.AppendLine("    {");
            builder.AppendLine("        T result = await valueTask.ConfigureAwait(false);");
            builder.AppendLine("        return result;");
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitServiceGen(StringBuilder builder, MessageGraph graph)
    {
        builder.AppendLine("internal static class ServiceGen");
        builder.AppendLine("{");
        HashSet<string> emitted = new();
        foreach (RequestBinding request in graph.Requests)
        {
            string field = HandlerFieldName(request.HandlerType);
            string typeName = Fq(request.HandlerType);
            if (!emitted.Add(typeName))
            {
                continue;
            }

            builder.Append("    internal static readonly ").Append(typeName).Append(' ').Append(field);
            builder.Append(" = new ").Append(typeName).AppendLine("();");
        }

        foreach (NotificationBinding notification in graph.Notifications)
        {
            foreach (INamedTypeSymbol handler in notification.HandlerTypes)
            {
                string field = HandlerFieldName(handler);
                string typeName = Fq(handler);
                if (!emitted.Add(typeName))
                {
                    continue;
                }

                builder.Append("    internal static readonly ").Append(typeName).Append(' ').Append(field);
                builder.Append(" = new ").Append(typeName).AppendLine("();");
            }
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitInterfaceSend(StringBuilder builder)
    {
        builder.AppendLine("    public global::System.Threading.Tasks.Task<TResponse> Send<TResponse>(global::TimeWarp.Mediator.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (request is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(request));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return SendCore<TResponse>(request, cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Threading.Tasks.Task Send<TRequest>(TRequest request, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("        where TRequest : global::TimeWarp.Mediator.IRequest");
        builder.AppendLine("    {");
        builder.AppendLine("        if (request is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(request));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return Send((object)request, cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private async global::System.Threading.Tasks.Task<TResponse> SendCore<TResponse>(global::TimeWarp.Mediator.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        object? boxed = await Send((object)request, cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        return (TResponse)boxed!;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitMonomorphicSend(StringBuilder builder, List<RequestBinding> requests, bool aot)
    {
        foreach (RequestBinding request in requests)
        {
            string requestType = Fq(request.RequestType);
            string responseType = Fq(request.ResponseType);
            string dispatch = DispatchName(request.RequestType);
            builder.Append("    public global::System.Threading.Tasks.ValueTask<").Append(responseType).Append("> Send(");
            builder.Append(requestType).AppendLine(" request, global::System.Threading.CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (request is null)");
            builder.AppendLine("        {");
            builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(request));");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.Append("        return ").Append(dispatch).Append('(');
            if (!aot)
            {
                builder.Append("ServiceProvider, ");
            }

            builder.AppendLine("request, cancellationToken);");
            builder.AppendLine("    }");
            builder.AppendLine();
        }
    }

    private static void EmitObjectSend(StringBuilder builder, List<RequestBinding> requests, bool aot)
    {
        builder.AppendLine("    public global::System.Threading.Tasks.Task<object?> Send(object request, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (request is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(request));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        switch (request)");
        builder.AppendLine("        {");
        HashSet<string> seen = new();
        foreach (RequestBinding request in requests)
        {
            string requestType = Fq(request.RequestType);
            if (!seen.Add(requestType))
            {
                continue;
            }

            string local = LocalName(request.RequestType);
            string dispatch = DispatchName(request.RequestType);
            builder.Append("            case ").Append(requestType).Append(' ').Append(local).AppendLine(":");
            builder.Append("                return Box(").Append(dispatch).Append('(');
            if (!aot)
            {
                builder.Append("ServiceProvider, ");
            }

            builder.Append(local).AppendLine(", cancellationToken));");
        }

        builder.AppendLine("            default:");
        builder.AppendLine("                throw new global::TimeWarp.Mediator.NoHandlerException(request.GetType());");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitPublish(StringBuilder builder, List<NotificationBinding> notifications, bool aot)
    {
        builder.AppendLine("    public global::System.Threading.Tasks.Task Publish<TNotification>(TNotification notification, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("        where TNotification : global::TimeWarp.Mediator.INotification");
        builder.AppendLine("    {");
        builder.AppendLine("        if (notification is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(notification));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return Publish((object)notification, cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Threading.Tasks.Task Publish(object notification, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (notification is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(notification));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        switch (notification)");
        builder.AppendLine("        {");
        HashSet<string> seen = new();
        foreach (NotificationBinding notification in notifications)
        {
            string typeName = Fq(notification.NotificationType);
            if (!seen.Add(typeName))
            {
                continue;
            }

            string local = LocalName(notification.NotificationType);
            builder.Append("            case ").Append(typeName).Append(' ').Append(local).AppendLine(":");
            builder.Append("                return Publish_").Append(MessageGraphBuilder.Sanitize(notification.NotificationType));
            builder.Append('(').Append(local).AppendLine(", cancellationToken);");
        }

        builder.AppendLine("            default:");
        builder.AppendLine("                return global::System.Threading.Tasks.Task.CompletedTask;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (NotificationBinding notification in notifications)
        {
            string typeName = Fq(notification.NotificationType);
            string method = "Publish_" + MessageGraphBuilder.Sanitize(notification.NotificationType);
            builder.Append("    private ");
            if (!aot)
            {
                builder.Append("");
            }

            builder.Append("async global::System.Threading.Tasks.Task ").Append(method).Append('(');
            builder.Append(typeName).AppendLine(" notification, global::System.Threading.CancellationToken cancellationToken)");
            builder.AppendLine("    {");
            int index = 0;
            foreach (INamedTypeSymbol handler in notification.HandlerTypes)
            {
                string handlerType = Fq(handler);
                string variable = "handler" + index;
                if (aot)
                {
                    builder.Append("        ").Append(handlerType).Append(' ').Append(variable);
                    builder.Append(" = ServiceGen.").Append(HandlerFieldName(handler)).AppendLine(";");
                }
                else
                {
                    builder.Append("        ").Append(handlerType).Append(' ').Append(variable);
                    builder.Append(" = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<");
                    builder.Append(handlerType).AppendLine(">(ServiceProvider);");
                }

                builder.Append("        await ").Append(variable).AppendLine(".Handle(notification, cancellationToken).ConfigureAwait(false);");
                index++;
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }
    }

    private static void EmitStreams(StringBuilder builder)
    {
        builder.AppendLine("    public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(global::TimeWarp.Mediator.IStreamRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        throw new global::System.NotSupportedException(\"Stream dispatch is deferred past M1 (004-001). Named pipelines (004-002) do not add streams.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Collections.Generic.IAsyncEnumerable<object?> CreateStream(object request, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        throw new global::System.NotSupportedException(\"Stream dispatch is deferred past M1 (004-001). Named pipelines (004-002) do not add streams.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitDispatchMethods(StringBuilder builder, List<RequestBinding> requests, bool aot)
    {
        foreach (RequestBinding request in requests)
        {
            string requestType = Fq(request.RequestType);
            string responseType = Fq(request.ResponseType);
            string handlerType = Fq(request.HandlerType);
            string dispatch = DispatchName(request.RequestType);
            builder.Append("    public static async global::System.Threading.Tasks.ValueTask<").Append(responseType).Append("> ").Append(dispatch).Append('(');
            if (!aot)
            {
                builder.Append("global::System.IServiceProvider scope, ");
            }

            builder.Append(requestType).AppendLine(" request, global::System.Threading.CancellationToken cancellationToken)");
            builder.AppendLine("    {");

            if (!aot)
            {
                builder.AppendLine("        if (scope is null)");
                builder.AppendLine("        {");
                builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(scope));");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        if (request is null)");
            builder.AppendLine("        {");
            builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(request));");
            builder.AppendLine("        }");
            builder.AppendLine();

            if (aot)
            {
                builder.Append("        ").Append(handlerType).Append(" handler = ServiceGen.").Append(HandlerFieldName(request.HandlerType)).AppendLine(";");
            }
            else
            {
                int behaviorIndex = 0;
                foreach (INamedTypeSymbol behavior in request.ClosedBehaviors)
                {
                    string behaviorType = Fq(behavior);
                    builder.Append("        ").Append(behaviorType).Append(" b").Append(behaviorIndex);
                    builder.Append(" = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<");
                    builder.Append(behaviorType).AppendLine(">(scope);");
                    behaviorIndex++;
                }

                builder.Append("        ").Append(handlerType);
                builder.Append(" handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<");
                builder.Append(handlerType).AppendLine(">(scope);");
            }

            if (!aot && request.ClosedBehaviors.Length > 0)
            {
                builder.Append("        return await b0.Handle(").AppendLine();
                builder.AppendLine("            request,");
                builder.Append("            next: ");
                EmitNextDelegate(builder, request, 0);
                builder.AppendLine(",");
                builder.AppendLine("            cancellationToken).ConfigureAwait(false);");
            }
            else if (request.IsUnitResponse)
            {
                builder.AppendLine("        await handler.Handle(request, cancellationToken).ConfigureAwait(false);");
                builder.AppendLine("        return global::TimeWarp.Mediator.Unit.Value;");
            }
            else
            {
                builder.AppendLine("        return await handler.Handle(request, cancellationToken).ConfigureAwait(false);");
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }
    }

    private static void EmitNextDelegate(StringBuilder builder, RequestBinding request, int behaviorIndex)
    {
        int nextIndex = behaviorIndex + 1;
        if (nextIndex >= request.ClosedBehaviors.Length)
        {
            if (request.IsUnitResponse)
            {
                builder.Append("async (global::System.Threading.CancellationToken t) => { await handler.Handle(request, t == default ? cancellationToken : t).ConfigureAwait(false); return global::TimeWarp.Mediator.Unit.Value; }");
            }
            else
            {
                builder.Append("(global::System.Threading.CancellationToken t) => handler.Handle(request, t == default ? cancellationToken : t)");
            }

            return;
        }

        builder.Append("(global::System.Threading.CancellationToken t").Append(behaviorIndex).Append(") => b").Append(nextIndex).Append(".Handle(request, next: ");
        EmitNextDelegate(builder, request, nextIndex);
        builder.Append(", t").Append(behaviorIndex).Append(" == default ? cancellationToken : t").Append(behaviorIndex).Append(')');
    }

    private static string EmitRegistration(MessageGraph graph)
    {
        string ns = graph.Membership.GeneratedNamespace;
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedMediatorServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedMediator(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (services is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(services));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<").Append(ns).Append(".Mediator>(services);").AppendLine();
        builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::TimeWarp.Mediator.IMediator>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(ns).AppendLine(".Mediator>(sp));");
        builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::TimeWarp.Mediator.ISender>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(ns).AppendLine(".Mediator>(sp));");
        builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::TimeWarp.Mediator.IPublisher>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(ns).AppendLine(".Mediator>(sp));");

        EmitHandlerRegistrations(builder, RequestsFor(graph, scope: null), NotificationsFor(graph, scope: null));

        builder.AppendLine("        return services;");
        builder.AppendLine("    }");

        List<INamedTypeSymbol> scopes = DistinctScopes(graph);
        if (scopes.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedMediator<TScope>(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (services is null)");
            builder.AppendLine("        {");
            builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(services));");
            builder.AppendLine("        }");
            builder.AppendLine();
            foreach (INamedTypeSymbol scope in scopes)
            {
                string suffix = ScopeSuffix(scope, graph);
                builder.Append("        if (typeof(TScope) == typeof(").Append(Fq(scope)).AppendLine("))");
                builder.AppendLine("        {");
                builder.Append("            AddGeneratedMediator_").Append(suffix).AppendLine("(services);");
                builder.AppendLine("            return services;");
                builder.AppendLine("        }");
            }

            builder.AppendLine("        throw new global::System.ArgumentException(\"No generated pipeline for scope '\" + typeof(TScope).FullName + \"'.\", nameof(TScope));");
            builder.AppendLine("    }");

            foreach (INamedTypeSymbol scope in scopes)
            {
                string suffix = ScopeSuffix(scope, graph);
                string senderType = ns + ".Sender_" + suffix;
                string publisherType = ns + ".Publisher_" + suffix;
                builder.AppendLine();
                builder.Append("    private static void AddGeneratedMediator_").Append(suffix).AppendLine("(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
                builder.AppendLine("    {");
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<").Append(senderType).AppendLine(">(services);");
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::TimeWarp.Mediator.ISender<").Append(Fq(scope)).Append(">>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(senderType).AppendLine(">(sp));");
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<").Append(publisherType).AppendLine(">(services);");
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::TimeWarp.Mediator.IPublisher<").Append(Fq(scope)).Append(">>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(publisherType).AppendLine(">(sp));");
                EmitHandlerRegistrations(builder, RequestsFor(graph, scope), NotificationsFor(graph, scope));
                builder.AppendLine("    }");
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitHandlerRegistrations(
        StringBuilder builder,
        List<RequestBinding> requests,
        List<NotificationBinding> notifications)
    {
        HashSet<string> registered = new();
        foreach (RequestBinding request in requests)
        {
            string handlerType = Fq(request.HandlerType);
            if (registered.Add(handlerType))
            {
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<").Append(handlerType).AppendLine(">(services);");
                if (request.IsUnitResponse)
                {
                    builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::TimeWarp.Mediator.IRequestHandler<").Append(Fq(request.RequestType)).Append(">>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(handlerType).AppendLine(">(sp));");
                }
                else
                {
                    builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::TimeWarp.Mediator.IRequestHandler<").Append(Fq(request.RequestType)).Append(", ").Append(Fq(request.ResponseType)).Append(">>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(handlerType).AppendLine(">(sp));");
                }
            }

            foreach (INamedTypeSymbol behavior in request.ClosedBehaviors)
            {
                string behaviorType = Fq(behavior);
                if (!registered.Add(behaviorType))
                {
                    continue;
                }

                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<").Append(behaviorType).AppendLine(">(services);");
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::TimeWarp.Mediator.IPipelineBehavior<").Append(Fq(request.RequestType)).Append(", ").Append(Fq(request.ResponseType)).Append(">>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(behaviorType).AppendLine(">(sp));");
            }
        }

        foreach (NotificationBinding notification in notifications)
        {
            foreach (INamedTypeSymbol handler in notification.HandlerTypes)
            {
                string handlerType = Fq(handler);
                if (!registered.Add(handlerType))
                {
                    continue;
                }

                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<").Append(handlerType).AppendLine(">(services);");
                builder.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::TimeWarp.Mediator.INotificationHandler<").Append(Fq(notification.NotificationType)).Append(">>(services, static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(handlerType).AppendLine(">(sp));");
            }
        }
    }

    private static string Fq(INamedTypeSymbol type)
    {
        return type.ToDisplayString(FullyQualified);
    }

    private static string DispatchName(INamedTypeSymbol requestType)
    {
        return "Dispatch_" + MessageGraphBuilder.Sanitize(requestType);
    }

    private static string HandlerFieldName(INamedTypeSymbol handlerType)
    {
        return MessageGraphBuilder.Sanitize(handlerType);
    }

    private static string LocalName(INamedTypeSymbol type)
    {
        string name = type.Name;
        if (string.IsNullOrEmpty(name))
        {
            return "value";
        }

        char first = char.ToLowerInvariant(name[0]);
        if (name.Length == 1)
        {
            return first.ToString();
        }

        return first + name.Substring(1);
    }

    private static List<INamedTypeSymbol> DistinctScopes(MessageGraph graph)
    {
        List<INamedTypeSymbol> scopes = new();
        foreach (RequestBinding request in graph.Requests)
        {
            AddScope(scopes, request.ScopeType);
        }

        foreach (NotificationBinding notification in graph.Notifications)
        {
            AddScope(scopes, notification.ScopeType);
        }

        scopes.Sort((left, right) => string.CompareOrdinal(left.ToDisplayString(), right.ToDisplayString()));
        return scopes;
    }

    private static void AddScope(List<INamedTypeSymbol> scopes, INamedTypeSymbol? scope)
    {
        if (scope is null)
        {
            return;
        }

        foreach (INamedTypeSymbol existing in scopes)
        {
            if (SymbolEqualityComparer.Default.Equals(existing, scope))
            {
                return;
            }
        }

        scopes.Add(scope);
    }

    private static string ScopeSuffix(INamedTypeSymbol scope, MessageGraph graph)
    {
        int sameName = 0;
        foreach (INamedTypeSymbol candidate in DistinctScopes(graph))
        {
            if (candidate.Name == scope.Name)
            {
                sameName++;
            }
        }

        return sameName <= 1 ? scope.Name : MessageGraphBuilder.Sanitize(scope);
    }

    private static List<RequestBinding> RequestsFor(MessageGraph graph, INamedTypeSymbol? scope)
    {
        List<RequestBinding> list = new();
        foreach (RequestBinding request in graph.Requests)
        {
            if (SymbolEqualityComparer.Default.Equals(request.ScopeType, scope))
            {
                list.Add(request);
            }
        }

        return list;
    }

    private static List<NotificationBinding> NotificationsFor(MessageGraph graph, INamedTypeSymbol? scope)
    {
        List<NotificationBinding> list = new();
        foreach (NotificationBinding notification in graph.Notifications)
        {
            if (SymbolEqualityComparer.Default.Equals(notification.ScopeType, scope))
            {
                list.Add(notification);
            }
        }

        return list;
    }
}
