<!-- Modified by Steven T. Cramer -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\timewarp-mediator-examples\timewarp-mediator-examples.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Windsor" />
    <PackageReference Include="Castle.Windsor.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
