name: NuGet Publish

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
  release:
    types: [published] # Triggered when a release is published via GitHub Releases UI or gh CLI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for MinVer to read all tags (e.g., contracts/v*, mediator/v*)

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Test Both Packages
        run: |
          # Build main package
          ./Build.ps1
          # Build contracts package  
          ./BuildContracts.ps1
        shell: pwsh

      - name: Check for prerelease packages
        id: check-prerelease
        run: |
          if ls ./Artifacts/*.nupkg | grep -q -E '\-alpha|\-beta'; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if version already published (PR only)
        if: github.event_name == 'pull_request'
        run: |
          VERSION=$(grep '<Version>' Directory.Build.props | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/')
          echo "Checking if TimeWarp.Mediator $VERSION is already published..."
          
          # Check TimeWarp.Mediator
          if dotnet nuget list TimeWarp.Mediator --source https://api.nuget.org/v3/index.json --prerelease | grep -q "TimeWarp.Mediator $VERSION"; then
            echo "⚠️ WARNING: TimeWarp.Mediator $VERSION is already published to NuGet.org"
            echo "❌ This version cannot be republished. Please increment the version in Directory.Build.props"
            exit 1
          else
            echo "✅ TimeWarp.Mediator $VERSION is not yet published"
          fi
          
          # Check TimeWarp.Mediator.Contracts  
          if dotnet nuget list TimeWarp.Mediator.Contracts --source https://api.nuget.org/v3/index.json --prerelease | grep -q "TimeWarp.Mediator.Contracts $VERSION"; then
            echo "⚠️ WARNING: TimeWarp.Mediator.Contracts $VERSION is already published to NuGet.org"
            echo "❌ This version cannot be republished. Please increment the version in Directory.Build.props"
            exit 1
          else
            echo "✅ TimeWarp.Mediator.Contracts $VERSION is not yet published"
          fi

      - name: Publish to NuGet.org (Releases only)
        if: github.event_name == 'release'
        run: |
          dotnet nuget push ./Artifacts/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        env:
          DOTNET_NUGET_SIGNATURE_VERIFICATION: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Packages-${{ github.run_number }}
          path: Artifacts/**/*