name: NuGet Publish

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/**'
  release:
    types: [published] # Triggered when a release is published via GitHub Releases UI or gh CLI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for MinVer to read all tags (e.g., contracts/v*, mediator/v*)

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Test Both Packages
        run: ./Build.ps1
        shell: pwsh

      - name: Check if version already published (PR only)
        if: github.event_name == 'pull_request'
        run: |
          VERSION=$(grep '<Version>' Directory.Build.props | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/')
          echo "Checking if TimeWarp.Mediator $VERSION is already published..."
          
          # Check TimeWarp.Mediator using package search
          if dotnet package search TimeWarp.Mediator --exact-match --prerelease | grep -q "$VERSION"; then
            echo "⚠️ WARNING: TimeWarp.Mediator $VERSION is already published to NuGet.org"
            echo "ℹ️ Consider incrementing the version in Directory.Build.props if you want to publish new changes"
          else
            echo "✅ TimeWarp.Mediator $VERSION is not yet published"
          fi
          
          # Check TimeWarp.Mediator.Contracts using package search
          if dotnet package search TimeWarp.Mediator.Contracts --exact-match --prerelease | grep -q "$VERSION"; then
            echo "⚠️ WARNING: TimeWarp.Mediator.Contracts $VERSION is already published to NuGet.org"
            echo "ℹ️ Consider incrementing the version in Directory.Build.props if you want to publish new changes"
          else
            echo "✅ TimeWarp.Mediator.Contracts $VERSION is not yet published"
          fi

      - name: Publish to NuGet.org (Releases only)
        if: github.event_name == 'release'
        run: |
          dotnet nuget push ./Artifacts/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        env:
          DOTNET_NUGET_SIGNATURE_VERIFICATION: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Packages-${{ github.run_number }}
          path: Artifacts/**/*