name: NuGet Publish

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
  release:
    types: [published] # Triggered when a release is published via GitHub Releases UI or gh CLI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for MinVer to read all tags (e.g., contracts/v*, mediator/v*)

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Test Both Packages
        run: |
          # Build main package
          ./Build.ps1
          # Build contracts package  
          ./BuildContracts.ps1
        shell: pwsh

      - name: Check for prerelease packages
        id: check-prerelease
        run: |
          if ls ./Artifacts/*.nupkg | grep -q -E '\-alpha|\-beta'; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to MyGet
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push ./Artifacts/*.nupkg \
            --api-key ${{ secrets.MYGET_TIMEWARP_MEDIATOR_CI_API_KEY }} \
            --source https://www.myget.org/F/timewarp-enterprises/api/v3/index.json \
            --skip-duplicate
        env:
          DOTNET_NUGET_SIGNATURE_VERIFICATION: false

      - name: Publish to NuGet.org (Stable only)
        if: github.event_name == 'release' && steps.check-prerelease.outputs.is_prerelease == 'false'
        run: |
          dotnet nuget push ./Artifacts/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        env:
          DOTNET_NUGET_SIGNATURE_VERIFICATION: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Packages-${{ github.run_number }}
          path: Artifacts/**/*